In [1]:
import numpy as np

In [12]:
c = np.array([[1, 1, 0], [1, 0, 0], [0, 0, 1]])
c

array([[1, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [ ]:
np.linalg.eig()

In [10]:
np.linalg.inv(x)

array([[ 1., -1.,  0.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  1.]])

In [11]:
x = np.array([[1, 1, 1], [0, 1, 1], [0, 0, 1]])
x@np.eye(3)@np.linalg.inv(x)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])